export interface DeckFormatOption {
  value: string;
  label: string;
  group: 'official' | 'digital' | 'casual' | 'community' | 'limited' | 'multiplayer';
}

export const DECK_FORMAT_OPTIONS: DeckFormatOption[] = [
  { value: 'Commander', label: 'Commander', group: 'official' },
  { value: 'Standard', label: 'Standard', group: 'official' },
  { value: 'Pioneer', label: 'Pioneer', group: 'official' },
  { value: 'Modern', label: 'Modern', group: 'official' },
  { value: 'Legacy', label: 'Legacy', group: 'official' },
  { value: 'Vintage', label: 'Vintage', group: 'official' },
  { value: 'Pauper', label: 'Pauper', group: 'official' },
  { value: 'Brawl', label: 'Brawl', group: 'official' },
  { value: 'Oathbreaker', label: 'Oathbreaker', group: 'official' },
  { value: 'Commander 1v1', label: 'Commander 1v1', group: 'official' },
  { value: 'Commander Limited', label: 'Commander Limited', group: 'official' },
  { value: 'Archenemy Commander', label: 'Archenemy Commander', group: 'official' },
  { value: 'Alchemy', label: 'Alchemy', group: 'digital' },
  { value: 'Historic', label: 'Historic', group: 'digital' },
  { value: 'Timeless', label: 'Timeless', group: 'digital' },
  { value: 'Explorer', label: 'Explorer', group: 'digital' },
  { value: 'Historic Brawl', label: 'Historic Brawl', group: 'digital' },
  { value: 'Standard Brawl', label: 'Standard Brawl', group: 'digital' },
  { value: 'Booster Draft', label: 'Booster Draft', group: 'limited' },
  { value: 'Pick-Two Draft', label: 'Pick-Two Draft', group: 'limited' },
  { value: 'Sealed Deck', label: 'Sealed Deck', group: 'limited' },
  { value: 'Team Booster Draft', label: 'Team Booster Draft', group: 'limited' },
  { value: 'Team Sealed Deck', label: 'Team Sealed Deck', group: 'limited' },
  { value: 'Conspiracy', label: 'Conspiracy', group: 'multiplayer' },
  { value: 'Two-Headed Giant', label: 'Two-Headed Giant', group: 'multiplayer' },
  { value: 'Planechase', label: 'Planechase', group: 'multiplayer' },
  { value: 'Archenemy', label: 'Archenemy', group: 'multiplayer' },
  { value: 'Freeform', label: 'Freeform', group: 'casual' },
  { value: 'Momir Basic', label: 'Momir Basic', group: 'casual' },
  { value: 'Pauper Commander', label: 'Pauper Commander', group: 'community' },
  { value: 'Duel Commander', label: 'Duel Commander', group: 'community' },
  { value: 'Penny Dreadful', label: 'Penny Dreadful', group: 'community' },
  { value: 'Gladiator', label: 'Gladiator', group: 'community' },
  { value: 'Old School', label: 'Old School', group: 'community' },
  { value: 'Premodern', label: 'Premodern', group: 'community' },
  { value: 'PreDH', label: 'PreDH', group: 'community' },
  { value: 'Canadian Highlander', label: 'Canadian Highlander', group: 'community' },
  { value: 'Australian Highlander', label: 'Australian Highlander', group: 'community' },
  { value: 'European Highlander', label: 'European Highlander', group: 'community' },
  { value: 'Tiny Leaders', label: 'Tiny Leaders', group: 'community' },
  { value: 'Cube', label: 'Cube', group: 'casual' },
  { value: 'Battle Box', label: 'Battle Box', group: 'casual' },
  { value: 'Kitchen Table', label: 'Kitchen Table', group: 'casual' }
];

export const DECK_PLAY_STYLE_SUGGESTIONS = [
  'Aggro',
  'Control',
  'Combo',
  'Midrange',
  'Tempo',
  'Ramp',
  'Burn',
  'Big Mana',
  'Stompy',
  'Zoo',
  'Tokens',
  'Voltron',
  'Aristocrats',
  'Reanimator',
  'Graveyard',
  'Sacrifice',
  'Lifegain',
  'Mill',
  'Discard',
  'Lands',
  'Landfall',
  'Prison',
  'Stax',
  'Pillow Fort',
  'Group Hug',
  'Group Slug',
  'Politics',
  'Spellslinger',
  'Storm',
  'Toolbox',
  'Blink',
  'Flicker',
  'Enchantress',
  'Artifacts',
  'Equipment',
  'Auras',
  'Go-wide',
  'Go-tall',
  'Kindred',
  'Good Stuff',
  'Hatebears',
  'Delver',
  'Stoneblade',
  'Tron',
  'Pod',
  'Dredge',
  'Prowess',
  'Infect',
  'Wheels',
  'Alternate Wincon',
  'Rule Zero',
  'Upgraded Precon',
  'Unmodified Precon'
] as const;

export const COMMANDER_BRACKET_OPTIONS = [
  'Bracket 1 - Exhibition',
  'Bracket 2 - Core',
  'Bracket 3 - Upgraded',
  'Bracket 4 - Optimized',
  'Bracket 5 - cEDH'
] as const;
